import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";


const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Lilac_Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<body
  className={`${openSans.variable} antialiased bg-[var(--background)] text-[var(--foreground)]`}
>
  {children}
</body>
    </html>
  );
}
